### PR TITLE
Add zimbatm hostname list

### LINKED ISSUE #13: See also "Hostnames and usernames to reserve"
Another list: https://zimbatm.github.io/hostnames-and-usernames-to-reserve/

### PR DESCRIPTION
**Pull request by ailox**
Closes #13 
This list from https://zimbatm.github.io/hostnames-and-usernames-to-reserve was simply taken and merged.

### CODE REVIEW

**Comment by ailox** [comment]
@dsignr should this be further split up into smaller changes?

**Comment by the94air** [comment]
This is nice!

**Comment by ailox** [comment]
Any changes required for this?

**Comment by dsignr** [comment]
Thank you for your contributions! Sorry for the delayed merge.

**Pull request merged**
